Histogram
```{r}
trees
hist( trees$Height)
hist( trees$Height,  main="Tree", ylab="Frequency",xlab="Height", col="blue")
hist( trees$Height,  main="Tree", ylab="Frequency",xlab="Height", col="blue",
      density=20, breaks=20    )# break to detail more the information
```
Density
```{r}
density = density(trees$Height)
plot(density)
```
density over the histogram
```{r}
#Execute with ctrl+shift+enter
hist(trees$Height, main=NULL, xlab=NULL, ylab = NULL)
par(new=TRUE)# overlap 
plot(density)
```
Dispersion
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main="Tree")
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Tree")
#pch change graphic elements
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Tree", pch=20)
```
Change type
```{r}
plot(trees$Girth, trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Tree", pch=20, type="l")
```
Flicker, decrease overlap
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab="Circumference", xlab="Volume", col="blue", main="Tree")
```
subtitles with categorical dimensions
```{r}
plot(CO2$conc, CO2$uptake,pch=20, col= CO2$Treatment)#col = to put a different color for each atribute 
#"bottom", "bottomleft", "left", "topleft", "top", "topright", "right" and "center"
legend("bottomright",legend=c("nonchilled","chilled"),cex=1, fill=c("black","red")) 
```
New data
```{r}
plot(trees)
```
Screen division
```{r}
#run with crtl+shift+enter
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```

