Cars: show speed and braking distance. 
```{r}
#install.packages("corrgram")
library(corrgram)
cars
dim(cars)
```
correlation between speed and braking distance
```{r}
cor(cars)
corrgram(cars, order=TRUE, lower.panel=panel.shade,
         upper.panel=panel.pie, text.panel=panel.txt,
         main="Carros")
```
Generating model using lm
predict car speed based on braking distance 
```{r}
modelo = lm(speed ~ dist, data=cars)
modelo
```
relation between variables and best adjustment line 
```{r}
#use Crtrl+ Shift + Enter
plot(speed ~ dist, data=cars, ylab = "Speed", xlab=" Distance", main="Cars")
abline(modelo)
```
prediction using the coeficients 
in what speed the braking distance is 22?
```{r}
modelo$coefficients
modelo$coefficients[1] + modelo$coefficients[2] * 22
```
Using predict
```{r}
predict(modelo,data.frame(dist = 22))
```
better look at the model
```{r}
summary(modelo)
modelo$coefficients
modelo$residuals
hist(modelo$residuals)
modelo$fitted.values
plot(modelo$fitted.values, cars$dist)
```

