```{r}
#install.packages("neuralnet")
#install.packages('mltools')
#install.packages('data.table')
#install.packages("caret", dependencies=T)
library(neuralnet)
library(mltools)
library(data.table)
library(caret)
```
standardize
```{r}
iris2 =  scale(iris[,1:4])
iris2 = as.data.frame(iris2)
#class add 
iris2$Species = iris$Species
iris2
```
training and test using caret 
```{r}
set.seed(1234)
partition = createDataPartition(1:dim(iris2)[1],p=.7)
iristraining = iris2[partition$Resample1,]
iristest = iris2[- partition$Resample1,]
dim(iristraining)
dim(iristest)
```
One hot encoding to the class 
```{r}
#attributes and class fusion
iristraining = cbind(iristraining[,1:4],one_hot(as.data.table( iristraining[,5])))
iristraining
```
model
```{r}
model = neuralnet( V1_setosa  + V1_versicolor  +  V1_virginica  ~ Sepal.Length + Sepal.Width +  Petal.Length + Petal.Width , iristraining, hidden=c(5,4))
print(model)
plot(model)
```
prediction
```{r}
test = compute(model,iristest[,1:4])
test$net.result
result = as.data.frame(test$net.result)
result
```
columns names as classes 
```{r}
names(result)[1] <- 'setosa'
names(result)[2] <- 'versicolor'
names(result)[3] <- 'virginica'
result
```
filling columns using class name
```{r}
result$class = colnames(result[,1:3])[max.col(result[,1:3], ties.method = 'first')]
result
```
performance review 
```{r}
confusion = table(result$class,iristest$Species)
confusion
sum(diag(confusion) * 100 / sum(confusion))
```
