
```{r}
#importing data, empty as NA, 
data = read.csv("Churn.csv", sep = ";", na.strings="", stringsAsFactors=T)## archive name, separation, when it find a empty place, it chances to NA, factor is a categorical data with a domain
head(data)
summary(data)
```
Columns
```{r}
#Correct name columns
colnames(data) = c("Id","Score","state","Gender","age","Patrimony","balance","Products","HaveCreditCard","Active","Wage","Exited")
head(data)
```
exploring data with categorical columns exploratory analysis
```{r}
#states
counts = table(data$state)
barplot(counts, main="states", xlab="states")
#Gender
counts = table(data$Gender)
barplot(counts, main="Genders", xlab="Genders")
```
Exploring numerical columns
```{r}
#Score
summary(data$Score)
boxplot(data$Score)
hist(data$Score)
```
age
```{r}
summary(data$age)
boxplot(data$age)
hist(data$age)
```
balance
```{r}
summary(data$balance)
boxplot(data$balance)
hist(data$balance)
```
Wage
```{r}
summary(data$Wage)
boxplot(data$Wage)
boxplot(data$Wage,outline = F)
```
missing values NAs
```{r}
#missing values NAs
data[!complete.cases(data),]
```
Wages
```{r}
#treating wage 
summary(data$Wage)
#see median
median(data$Wage,na.rm = T)
#assign median value to NA
data[is.na(data$Wage),]$Wage = median(data$Wage,na.rm = T) # na.rm = true to remove the NA values from de calculation
#search if we still have some NAs data in wege
data[!complete.cases(data$Wage),]
```
gender without pattern
```{r}
#see values
unique(data$Gender)
summary(data$Gender)
#change F and fem to female
# "" ,M to male (moda)
data[is.na(data$Gender) | data$Gender == "M" ,]$Gender = "Masculino" 
data[data$Gender == "F" | data$Gender == "Fem", ]$Gender = "Feminino" 
#see results
summary(data$Gender)
#remove unused levels
data$Gender =   factor(data$Gender) 
#view again
summary(data$Gender)
```
ages over the domain
```{r}
summary(data$age)
#see ages out of the normal domain
data[data$age<0 | data$age>110 ,]$age
#no NAs
data[is.na(data$age),]
#fill with median
median(data$age)
#change
data[data$age<0 | data$age>110 ,]$age = median(data$age) 
#search again for ages out of the pattern
data[data$age<0 | data$age>110 ,]
summary(data$age)
```
duplicated data
```{r}
#search for duplicated data with ID
x =  data[duplicated(data$Id),]
x
#ID 81 is duplicated
#excluding by ID, 82
data = data[-c(82),]

#search duplicated lines
data[data$Id == x$Id ,]
#search again for duplicated lines
x =  data[duplicated(data$Id),]
x
```
state out of the domain
```{r}
#put of the categorical domain
unique(data$state)
summary(data$state)
#fill with de moda, RS
data[!data$state %in% c("RS","SC","PR"),]$state = "RS"
summary(data$state)
#remove unused factors
data$state =   factor(data$state)
#visualize again
summary(data$state)
```
Outliers
```{r}
#outliers, create a parameter with the default deviation
desv = sd(data$Wage, na.rm = T)
desv
data[data$Wage >= 2 *desv  , ]$Wage
#another form with similar result but without NAs
boxplot(data$Wage)
boxplot(data$Wage, outline = F)
x = boxplot(data$Wage)$out
x
#updating all to median
median(data$Wage)
data[data$Wage >= 2 *desv  , ]$Wage = median(data$Wage)
#check if outliers was erased
data[data$Wage >= 2 *desv  , ]$Wage
```

