```{r}
#install.packages("igraph")
library(igraph)
```
graph creation
```{r}
dist = graph(edges=c("A","C","A","B","B","E","B","F","C","D","G","H","D","H","E","H","F","G"),directed=TRUE)
plot(dist)
```
weight definition
```{r}
#weights to represent distance ( in the edges)
E(dist)$weight = c(2,1,2,1,2,1,1,3,1)
plot(dist, edge.label = E(dist)$weight)
tkplot(dist, edge.label = E(dist)$weight, vertex.color="white")
```
Search distance 

```{r}
#distance between vertex calculation
distances(dist,V(dist)$name=="A",V(dist)$name=="H")
#graph verification
plot(dist, edge.label = E(dist)$weight)
#search for the shortest path 
#output vertices and edges return list. both to return both hehe
path = shortest_paths(dist,V(dist)$name=="A",V(dist)$name=="H", output=c("both"))
path$vpath
#checking
plot(dist, edge.label = E(dist)$weight)
```
creating graph using the shortest path 
```{r}
#run through vertex
for(i in 1:length(V(dist)))
{ #if it was in the list of shortest vertex , paint with green else paint with grey
V(dist)$color[i] <- ifelse(i  %in% as.vector(unlist(path$vpath))
 ,"green","gray")
}

for(i in 1:length(E(dist)))
{  #if it was in the list of shortest vertex , paint with green else paint with grey
E(dist)$color[i] <- ifelse(i  %in% as.vector(unlist(path$epath))
 , "green","gray")
}

plot(dist, edge.label = E(dist)$weight)
```

